import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../theme/app_colors.dart';

class VoiceToDocScreen extends StatefulWidget {
  const VoiceToDocScreen({super.key});
  @override
  State<VoiceToDocScreen> createState() => _VoiceToDocScreenState();
}

class _VoiceToDocScreenState extends State<VoiceToDocScreen>
    with SingleTickerProviderStateMixin {
  static const _channel = MethodChannel('com.dakshitha.battery_barter/speech');

  bool _listening = false;
  bool _available = false;
  bool _exporting = false;
  String _status = '';
  String _partial = '';
  double _soundLevel = 0;
  String _transcript = '';
  String _format = 'txt';

  final _editCtrl = TextEditingController();
  bool _editing = false;

  late AnimationController _pulseCtrl;
  late Animation<double> _pulse;

  @override
  void initState() {
    super.initState();
    _pulseCtrl = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 700))
      ..repeat(reverse: true);
    _pulse = Tween<double>(begin: 0.9, end: 1.1)
        .animate(CurvedAnimation(parent: _pulseCtrl, curve: Curves.easeInOut));
    _channel.setMethodCallHandler(_handleNative);
    _checkAvailable();
  }

  @override
  void dispose() {
    if (_listening) _channel.invokeMethod('stopListening');
    _pulseCtrl.dispose();
    _editCtrl.dispose();
    super.dispose();
  }

  Future<void> _checkAvailable() async {
    // Always available on Android — permission requested on first tap
    setState(() => _available = true);
  }

  Future<dynamic> _handleNative(MethodCall call) async {
    switch (call.method) {
      case 'onStatus':
        setState(() => _status = call.arguments as String);
        break;
      case 'onSoundLevel':
        setState(() => _soundLevel = (call.arguments as double).clamp(0, 10));
        break;
      case 'onPartial':
        setState(() => _partial = call.arguments as String);
        break;
      case 'onResult':
        final words = call.arguments as String;
        if (words.isNotEmpty) {
          setState(() {
            if (_transcript.isNotEmpty) _transcript += ' ';
            _transcript += words;
            _partial = '';
          });
        }
        break;
      case 'onError':
        final errMsg = call.arguments as String;
        setState(() {
          _status = 'error';
          _partial = '';
          _listening = false;
        });
        if (errMsg == 'permission_denied') {
          _snack('Microphone permission denied. Please allow in Settings.');
        }
        break;
    }
  }

  Future<void> _toggleListen() async {
    if (_listening) {
      await _channel.invokeMethod('stopListening');
      setState(() {
        _listening = false;
        _partial = '';
        _status = '';
      });
    } else {
      try {
        await _channel.invokeMethod('startListening');
        setState(() {
          _listening = true;
          _status = 'listening';
        });
      } catch (e) {
        _snack('Could not start: $e');
      }
    }
  }

  bool get _hasText => _transcript.trim().isNotEmpty;

  String get _displayText {
    if (_partial.isNotEmpty) return '$_transcript $_partial';
    return _transcript;
  }

  String get _analysedContent {
    final text = _transcript.trim();
    if (text.isEmpty) return '';
    switch (_format) {
      case 'csv':
        return _toCSV(text);
      case 'doc':
        return _toDoc(text);
      default:
        return text;
    }
  }

  String _toCSV(String text) {
    if (text.contains(':')) {
      final rows = text.split('\n').where((l) => l.trim().isNotEmpty).map((l) {
        final parts = l.split(':');
        if (parts.length >= 2) {
          return '"${parts[0].trim()}","${parts.sublist(1).join(':').trim()}"';
        }
        return '"$l",""';
      }).join('\n');
      return 'Field,Value\n$rows';
    }
    final lines = text
        .split(RegExp(r'[\n,]'))
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();
    final rows = lines
        .asMap()
        .entries
        .map((e) => '${e.key + 1},"${e.value}"')
        .join('\n');
    return 'No,Item\n$rows';
  }

  String _toDoc(String text) {
    final now = DateTime.now();
    final words = text.split(' ').length;
    return '''DOCUMENT
Generated by AmpUp Voice-to-Doc
Date: ${now.day}/${now.month}/${now.year}  Time: ${now.hour}:${now.minute.toString().padLeft(2, '0')}
Word count: $words
${'=' * 40}

$text

${'=' * 40}
END OF DOCUMENT''';
  }

  Future<void> _export() async {
    if (!_hasText) {
      _snack('Record something first.');
      return;
    }
    setState(() => _exporting = true);
    try {
      final dir = await getTemporaryDirectory();
      final now = DateTime.now();
      final file =
          File('${dir.path}/ampup_${now.millisecondsSinceEpoch}.$_format');
      await file.writeAsString(_analysedContent);
      await Share.shareXFiles([XFile(file.path)], subject: 'Voice Doc — AmpUp');
    } catch (e) {
      _snack('Export failed: $e');
    } finally {
      if (mounted) setState(() => _exporting = false);
    }
  }

  Future<void> _copy() async {
    if (!_hasText) {
      _snack('Nothing to copy.');
      return;
    }
    await Clipboard.setData(ClipboardData(text: _transcript));
    _snack('Copied!');
  }

  void _snack(String msg) =>
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(msg),
          behavior: SnackBarBehavior.floating,
          duration: const Duration(seconds: 2)));

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor:
          isDark ? const Color(0xFF0F172A) : const Color(0xFFF1F5F9),
      body: SafeArea(
        child: Column(children: [
          // Header
          Container(
            padding: const EdgeInsets.fromLTRB(8, 12, 16, 12),
            decoration: BoxDecoration(
                color: isDark ? const Color(0xFF0F172A) : Colors.white,
                border: Border(
                    bottom: BorderSide(
                        color: isDark
                            ? Colors.white.withOpacity(0.06)
                            : Colors.black.withOpacity(0.06)))),
            child: Row(children: [
              IconButton(
                  icon: Icon(Icons.arrow_back_ios_rounded,
                      color: isDark ? Colors.white : const Color(0xFF0F172A)),
                  onPressed: () {
                    if (_listening) _channel.invokeMethod('stopListening');
                    Navigator.pop(context);
                  }),
              Expanded(
                  child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                    Text('Voice to Doc',
                        style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w700,
                            color: isDark
                                ? Colors.white
                                : const Color(0xFF0F172A))),
                    Text(
                        _listening
                            ? (_status == 'processing'
                                ? 'Processing...'
                                : 'Listening...')
                            : 'Tap mic to start recording',
                        style: TextStyle(
                            fontSize: 11,
                            color: _listening
                                ? const Color(0xFFEF4444)
                                : (isDark
                                    ? Colors.white.withOpacity(0.4)
                                    : Colors.black.withOpacity(0.4)))),
                  ])),
              if (_hasText)
                GestureDetector(
                    onTap: () => setState(() {
                          _transcript = '';
                          _partial = '';
                        }),
                    child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                            color: isDark
                                ? Colors.white.withOpacity(0.06)
                                : Colors.black.withOpacity(0.05),
                            borderRadius: BorderRadius.circular(10)),
                        child: Text('Clear',
                            style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                                color: isDark
                                    ? Colors.white.withOpacity(0.5)
                                    : Colors.black.withOpacity(0.45))))),
            ]),
          ),

          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(children: [
                // Sound bars
                SizedBox(
                  height: 32,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: List.generate(24, (i) {
                      final h = _listening
                          ? (6 + _soundLevel * 2.2 * (0.4 + (i % 5) * 0.12))
                              .clamp(3.0, 28.0)
                          : 3.0;
                      return AnimatedContainer(
                          duration: const Duration(milliseconds: 80),
                          width: 3,
                          height: h,
                          margin: const EdgeInsets.symmetric(horizontal: 1.5),
                          decoration: BoxDecoration(
                              color: _listening
                                  ? const Color(0xFFEF4444)
                                      .withOpacity(0.5 + (i % 3) * 0.15)
                                  : (isDark
                                      ? Colors.white.withOpacity(0.08)
                                      : Colors.black.withOpacity(0.06)),
                              borderRadius: BorderRadius.circular(3)));
                    }),
                  ),
                ),

                const SizedBox(height: 16),

                // Mic button
                GestureDetector(
                  onTap: _available ? _toggleListen : null,
                  child: AnimatedBuilder(
                    animation: _pulse,
                    builder: (_, child) => Transform.scale(
                        scale: _listening ? _pulse.value : 1.0, child: child),
                    child: Container(
                        width: 90,
                        height: 90,
                        decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            gradient: LinearGradient(
                                begin: Alignment.topLeft,
                                end: Alignment.bottomRight,
                                colors: _listening
                                    ? [
                                        const Color(0xFFEF4444),
                                        const Color(0xFFDC2626)
                                      ]
                                    : [
                                        const Color(0xFFEC4899),
                                        const Color(0xFF8B5CF6)
                                      ]),
                            boxShadow: [
                              BoxShadow(
                                  color: (_listening
                                          ? const Color(0xFFEF4444)
                                          : const Color(0xFFEC4899))
                                      .withOpacity(0.45),
                                  blurRadius: _listening ? 30 : 16,
                                  spreadRadius: _listening ? 4 : 0,
                                  offset: const Offset(0, 5))
                            ]),
                        child: Icon(
                            _listening ? Icons.stop_rounded : Icons.mic_rounded,
                            color: Colors.white,
                            size: 40)),
                  ),
                ),

                const SizedBox(height: 10),
                Text(_listening ? 'Tap to stop' : 'Tap to record',
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: _listening
                            ? const Color(0xFFEF4444)
                            : (isDark
                                ? Colors.white.withOpacity(0.45)
                                : Colors.black.withOpacity(0.4)))),

                const SizedBox(height: 20),

                // Transcript
                Container(
                  width: double.infinity,
                  constraints: const BoxConstraints(minHeight: 160),
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                      color: isDark
                          ? Colors.white.withOpacity(0.04)
                          : Colors.white,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                          color: _listening
                              ? const Color(0xFFEF4444).withOpacity(0.4)
                              : (isDark
                                  ? Colors.white.withOpacity(0.07)
                                  : Colors.black.withOpacity(0.07)),
                          width: _listening ? 2 : 1)),
                  child: _editing
                      ? Column(children: [
                          TextField(
                              controller: _editCtrl,
                              maxLines: null,
                              style: TextStyle(
                                  fontSize: 15,
                                  height: 1.65,
                                  color: isDark
                                      ? Colors.white
                                      : const Color(0xFF0F172A)),
                              decoration: InputDecoration(
                                  border: InputBorder.none,
                                  hintText: 'Edit transcript...',
                                  hintStyle: TextStyle(
                                      color: isDark
                                          ? Colors.white.withOpacity(0.3)
                                          : Colors.black.withOpacity(0.3)))),
                          Row(children: [
                            Expanded(
                                child: GestureDetector(
                                    onTap: () =>
                                        setState(() => _editing = false),
                                    child: Container(
                                        height: 36,
                                        decoration: BoxDecoration(
                                            borderRadius:
                                                BorderRadius.circular(10),
                                            color: isDark
                                                ? Colors.white.withOpacity(0.06)
                                                : Colors.black
                                                    .withOpacity(0.05)),
                                        child: Center(
                                            child: Text('Cancel',
                                                style: TextStyle(
                                                    fontSize: 13,
                                                    color: isDark
                                                        ? Colors.white
                                                        : Colors.black)))))),
                            const SizedBox(width: 10),
                            Expanded(
                                child: GestureDetector(
                                    onTap: () => setState(() {
                                          _transcript = _editCtrl.text;
                                          _editing = false;
                                        }),
                                    child: Container(
                                        height: 36,
                                        decoration: BoxDecoration(
                                            borderRadius:
                                                BorderRadius.circular(10),
                                            color: const Color(0xFFEC4899)),
                                        child: const Center(
                                            child: Text('Save',
                                                style: TextStyle(
                                                    fontSize: 13,
                                                    fontWeight: FontWeight.w700,
                                                    color: Colors.white)))))),
                          ]),
                        ])
                      : _displayText.isEmpty
                          ? Center(
                              child: Padding(
                                  padding: const EdgeInsets.all(20),
                                  child: Text(
                                      _listening
                                          ? 'Speak now...'
                                          : 'Your speech will appear here',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontSize: 14,
                                          color: isDark
                                              ? Colors.white.withOpacity(0.25)
                                              : Colors.black
                                                  .withOpacity(0.25)))))
                          : Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                  RichText(
                                      text: TextSpan(
                                          style: TextStyle(
                                              fontSize: 15,
                                              height: 1.65,
                                              color: isDark
                                                  ? Colors.white
                                                  : const Color(0xFF0F172A)),
                                          children: [
                                        TextSpan(text: _transcript),
                                        if (_partial.isNotEmpty)
                                          TextSpan(
                                              text: ' $_partial',
                                              style: TextStyle(
                                                  color: const Color(0xFFEC4899)
                                                      .withOpacity(0.7),
                                                  fontStyle: FontStyle.italic)),
                                      ])),
                                  if (_hasText) ...[
                                    const SizedBox(height: 10),
                                    Row(children: [
                                      Icon(Icons.text_fields_rounded,
                                          size: 12,
                                          color: isDark
                                              ? Colors.white.withOpacity(0.3)
                                              : Colors.black.withOpacity(0.3)),
                                      const SizedBox(width: 4),
                                      Text(
                                          '${_transcript.trim().split(' ').where((w) => w.isNotEmpty).length} words',
                                          style: TextStyle(
                                              fontSize: 11,
                                              color: isDark
                                                  ? Colors.white
                                                      .withOpacity(0.35)
                                                  : Colors.black
                                                      .withOpacity(0.35))),
                                      const Spacer(),
                                      GestureDetector(
                                          onTap: () {
                                            _editCtrl.text = _transcript;
                                            setState(() => _editing = true);
                                          },
                                          child: Row(children: [
                                            Icon(Icons.edit_rounded,
                                                size: 12,
                                                color: const Color(0xFFEC4899)),
                                            const SizedBox(width: 4),
                                            const Text('Edit',
                                                style: TextStyle(
                                                    fontSize: 11,
                                                    fontWeight: FontWeight.w600,
                                                    color: Color(0xFFEC4899))),
                                          ])),
                                    ]),
                                  ],
                                ]),
                ),

                if (_hasText) ...[
                  const SizedBox(height: 20),

                  // Format picker
                  Align(
                      alignment: Alignment.centerLeft,
                      child: Text('EXPORT FORMAT',
                          style: TextStyle(
                              fontSize: 10,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 1.2,
                              color: isDark
                                  ? Colors.white.withOpacity(0.35)
                                  : Colors.black.withOpacity(0.35)))),
                  const SizedBox(height: 10),
                  Row(children: [
                    _FormatChip(
                        icon: Icons.description_rounded,
                        label: 'Text',
                        ext: '.txt',
                        selected: _format == 'txt',
                        color: const Color(0xFF3B82F6),
                        isDark: isDark,
                        onTap: () => setState(() => _format = 'txt')),
                    const SizedBox(width: 10),
                    _FormatChip(
                        icon: Icons.table_chart_rounded,
                        label: 'Spreadsheet',
                        ext: '.csv',
                        selected: _format == 'csv',
                        color: const Color(0xFF22C55E),
                        isDark: isDark,
                        onTap: () => setState(() => _format = 'csv')),
                    const SizedBox(width: 10),
                    _FormatChip(
                        icon: Icons.article_rounded,
                        label: 'Document',
                        ext: '.doc',
                        selected: _format == 'doc',
                        color: const Color(0xFF8B5CF6),
                        isDark: isDark,
                        onTap: () => setState(() => _format = 'doc')),
                  ]),

                  const SizedBox(height: 16),

                  // Preview
                  Align(
                      alignment: Alignment.centerLeft,
                      child: Text('PREVIEW',
                          style: TextStyle(
                              fontSize: 10,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 1.2,
                              color: isDark
                                  ? Colors.white.withOpacity(0.35)
                                  : Colors.black.withOpacity(0.35)))),
                  const SizedBox(height: 8),
                  Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(14),
                      decoration: BoxDecoration(
                          color: isDark
                              ? Colors.black.withOpacity(0.3)
                              : const Color(0xFFF8FAFF),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                              color: isDark
                                  ? Colors.white.withOpacity(0.06)
                                  : Colors.black.withOpacity(0.06))),
                      child: Text(
                          _analysedContent.length > 300
                              ? '${_analysedContent.substring(0, 300)}...'
                              : _analysedContent,
                          style: TextStyle(
                              fontSize: 11.5,
                              height: 1.6,
                              fontFamily: 'monospace',
                              color: isDark
                                  ? Colors.white.withOpacity(0.6)
                                  : const Color(0xFF374151)))),

                  const SizedBox(height: 20),

                  // Export
                  GestureDetector(
                    onTap: _exporting ? null : _export,
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(18),
                      decoration: BoxDecoration(
                          gradient: const LinearGradient(
                              colors: [Color(0xFFEC4899), Color(0xFF8B5CF6)],
                              begin: Alignment.topLeft,
                              end: Alignment.bottomRight),
                          borderRadius: BorderRadius.circular(16),
                          boxShadow: [
                            BoxShadow(
                                color: const Color(0xFFEC4899).withOpacity(0.4),
                                blurRadius: 14,
                                offset: const Offset(0, 5))
                          ]),
                      child: Row(children: [
                        Container(
                            width: 48,
                            height: 48,
                            decoration: BoxDecoration(
                                color: Colors.white.withOpacity(0.2),
                                borderRadius: BorderRadius.circular(14)),
                            child: _exporting
                                ? const Center(
                                    child: SizedBox(
                                        width: 20,
                                        height: 20,
                                        child: CircularProgressIndicator(
                                            color: Colors.white,
                                            strokeWidth: 2)))
                                : const Icon(Icons.share_rounded,
                                    color: Colors.white, size: 24)),
                        const SizedBox(width: 14),
                        Expanded(
                            child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                              Text('Export & Share as .$_format',
                                  style: const TextStyle(
                                      color: Colors.white,
                                      fontWeight: FontWeight.w700,
                                      fontSize: 15)),
                              const Text('WhatsApp, Email, Drive & more',
                                  style: TextStyle(
                                      color: Colors.white70, fontSize: 12)),
                            ])),
                        const Icon(Icons.arrow_forward_ios_rounded,
                            color: Colors.white70, size: 16),
                      ]),
                    ),
                  ),
                  const SizedBox(height: 10),
                  GestureDetector(
                    onTap: _copy,
                    child: Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                            color: isDark
                                ? Colors.white.withOpacity(0.04)
                                : Colors.white,
                            borderRadius: BorderRadius.circular(14),
                            border: Border.all(
                                color: const Color(0xFF6366F1).withOpacity(0.3),
                                width: 1.5)),
                        child: Row(children: [
                          Container(
                              width: 38,
                              height: 38,
                              decoration: BoxDecoration(
                                  color:
                                      const Color(0xFF6366F1).withOpacity(0.1),
                                  borderRadius: BorderRadius.circular(10)),
                              child: const Icon(Icons.copy_rounded,
                                  color: Color(0xFF6366F1), size: 18)),
                          const SizedBox(width: 12),
                          Text('Copy raw text',
                              style: TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                  color: isDark
                                      ? Colors.white
                                      : const Color(0xFF0F172A))),
                        ])),
                  ),
                ],
                const SizedBox(height: 24),
              ]),
            ),
          ),
        ]),
      ),
    );
  }
}

class _FormatChip extends StatelessWidget {
  final IconData icon;
  final String label, ext;
  final bool selected, isDark;
  final Color color;
  final VoidCallback onTap;
  const _FormatChip(
      {required this.icon,
      required this.label,
      required this.ext,
      required this.selected,
      required this.isDark,
      required this.color,
      required this.onTap});
  @override
  Widget build(BuildContext context) => Expanded(
      child: GestureDetector(
          onTap: onTap,
          child: AnimatedContainer(
              duration: const Duration(milliseconds: 180),
              padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 6),
              decoration: BoxDecoration(
                  color: selected
                      ? color.withOpacity(isDark ? 0.15 : 0.08)
                      : (isDark
                          ? Colors.white.withOpacity(0.04)
                          : Colors.white),
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                      color: selected
                          ? color
                          : (isDark
                              ? Colors.white.withOpacity(0.07)
                              : Colors.black.withOpacity(0.07)),
                      width: selected ? 2 : 1)),
              child: Column(children: [
                Icon(icon,
                    color: selected
                        ? color
                        : (isDark
                            ? Colors.white.withOpacity(0.35)
                            : Colors.black.withOpacity(0.3)),
                    size: 20),
                const SizedBox(height: 5),
                Text(label,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.w600,
                        color: selected
                            ? color
                            : (isDark
                                ? Colors.white.withOpacity(0.5)
                                : Colors.black.withOpacity(0.45)))),
                Text(ext,
                    style: TextStyle(
                        fontSize: 9,
                        color: selected
                            ? color.withOpacity(0.7)
                            : (isDark
                                ? Colors.white.withOpacity(0.25)
                                : Colors.black.withOpacity(0.25)))),
              ]))));
}

